apiVersion: v1
kind: ConfigMap
metadata:
  name: spring-data-service
data:
  application.yml: |-
    spring.data.cassandra.contact-points: cluster1-dc1-service.cass-operator
    spring.data.cassandra.port: 9042
    spring.data.cassandra.keyspace-name: betterbotz
    spring.data.cassandra.local-datacenter: dc1
    spring.data.cassandra.schema-action: create-if-not-exists
    spring.data.cassandra.rest.basePath: /api