apiVersion: v1
kind: ConfigMap
metadata:
  name: gateway-service
data:
  application.yml: |-
    spring:
      cloud:
        gateway:
          routes:
          - id: rewrite_products
            predicates:
            - Path=/api/products/**
            uri: http://spring-boot-service.spring-boot-service.svc.cluster.local:80
            filters:
            - RewritePath=/(?<remains>.*), /$\{remains}
          - id: rewrite_orders
            predicates:
            - Path=/api/orders/**
            uri: http://spring-data-service.spring-data-service.svc.cluster.local:80
            filters:
            - RewritePath=/(?<remains>.*), /$\{remains}